### PR TITLE
Fix edit action bar to bottom of text area

### LINKED ISSUE #4395: Save button footer fixed to bottom
- [x] Feature Idea

When editing a post, would be nice if the button actions footer was fixed/sticky to the bottom of the screen. Especially for longer posts. Currently, you have to scroll all the way down to find the Cancel/Save buttons

### PR DESCRIPTION
**Pull request by Glazy**
Before this change the 'Save' and 'Cancel' buttons would move on/off the
screen as you scrolled which meant you had to scroll all the way to the
bottom of a post to select either of the options.

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)
- desktop

**Release notes for users (delete if codebase-only change)**
- Fix 'Save' and 'Cancel' buttons to bottom of window when editing a post for easier access.

**Related issues (delete if you don't know of any)**
Closes #4395 

screenshot 2018-12-08 at 02 17 04

As you can see from the scrollbar in the above screenshot we aren't at the bottom of the post but you can still access the action bar buttons.

### CODE REVIEW

File: src/views/thread/style.js [hunk 1]
```diff
@@ -609,6 +609,13 @@ export const WatercoolerActionBarContainer = styled(ActionBarContainer)`
   margin-bottom: 16px;
 `;
 
+export const FixedBottomActionBarContainer = styled(ActionBarContainer)`
+  z-index: 1;
+  bottom: 0;
+  position: sticky;
```
Comment (mxstbr) [inline src/views/thread/style.js:615]: What is the fallback behaviour if a browser doesn't support `sticky`, will anything break?

**Review by mxstbr — COMMENTED** [review]
Thanks for digging into this, just one tiny question!

File: src/views/thread/style.js (hunk 1 above)
Comment (Glazy) [reply src/views/thread/style.js:615]: Double checked this in IE11 and the behaviour remains the same as before this change :+1:

**Review by mxstbr — APPROVED** [review]
This LGTM, thanks so much! Let's wait for @brianlovin's review 👍

**Comment by brianlovin** [comment]
This is a really wonderful QoL fix - thank you @Glazy!!

**Comment by megaroeny** [comment]
I had no idea about the `sticky` CSS property! 😂 Awesome!
