### PR TITLE
Fix hyperion memory leak

### LINKED ISSUE #4573: Fix hyperion styled-components memory leak
We need to manually call `sheet.complete()` if an error happens, see 
https://github.com/styled-components/styled-components/issues/1624#issuecomment-425382979

### PR DESCRIPTION
**Pull request by mxstbr**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

**Related issues (delete if you don't know of any)**
Closes #4573

@brianlovin this might be causing the response time jumps every couple days? Not sure, but it should definitely alleviate some memory pressure on our hyperion instances.

### CODE REVIEW

File: hyperion/renderer/index.js [hunk 1]
```diff
@@ -189,6 +189,8 @@ const renderer = (req: express$Request, res: express$Response) => {
       );
     })
     .catch(err => {
+      // Avoid memory leaks, see https://github.com/styled-components/styled-components/issues/1624#issuecomment-425382979
+      sheet.complete();
```
Comment (lucasfeliciano) [inline hyperion/renderer/index.js:193]: This api has changed.

Currently is `sheet.seal()` instead of `sheet.complete()`

Also would be even better if you call it on the `finally` block instead of catch. :)

**Comment by lucasfeliciano** [comment]
> this might be causing the response time jumps every couple days? Not sure, but it should definitely alleviate some memory pressure on our hyperion instances.

This was our case as well, the kubernetes pod would just stop responding and restart at some point and some requests would just stay in a limbo state.

Just to give you some idea about this change:

image

You can see how fest the memory would increase in the beginning of the graph.
When it goes down  means that a deploy happened.
And after the last deploy you see that the memory increase is much smoother

File: hyperion/renderer/index.js (hunk 1 above)
Comment (mxstbr) [reply hyperion/renderer/index.js:193]: We're on v3, so it's `.complete` right?

**Comment by mxstbr** [comment]
@lucasfeliciano would you mind updating the styled-components documentation to include this information? :pray: Otherwise everybody's going to run into this issue!

File: hyperion/renderer/index.js (hunk 1 above)
Comment (lucasfeliciano) [reply hyperion/renderer/index.js:193]: I'm 100% sure when the API changed, we are on v6 so it might be that you need to call `.complete` instead

**Review by brianlovin — APPROVED** [review]
Ship it!
