### PR TITLE
Fix DM pagination

### LINKED ISSUE #3273: [Mobile] Fix DM thread pagination
The app currently crashes if you scroll down and trigger a pagination event while in the Messages tab

### PR DESCRIPTION
**Pull request by brianlovin**
**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- mobile

Closes #3273

### CODE REVIEW

File: mobile/views/DirectMessages/components/DirectMessageThreadsList.js [hunk 1]
```diff
@@ -31,10 +32,13 @@ const DirectMessageThreadsList = (props: Props) => {
   const { isLoading, hasError, data: { user }, navigation } = props;
   if (user) {
     const { pageInfo, edges } = user.directMessageThreadsConnection;
+    const nodes = edges.map(e => e && e.node);
+    const unique = deduplicateChildren(nodes, 'id');
```
Comment (mxstbr) [inline mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: Why would the server ever send duplicate DM threads?! :scream: We should fix that server-side!

Comment (brianlovin) [reply mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: I don't think it's the server, I think it's the infinite scroll component firing a `fetchMore` multiple times while it's still `refetch`ing - might need to just add in some `shouldComponentUpdate` logic to try and prevent this from happening.

Comment (brianlovin) [reply mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: It might also be the server, too - not sure if we have the same problem in the web app

Comment (mxstbr) [reply mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: I thought I made the `InfiniteList` be very clear about only ever calling `fetchMore` once?

https://github.com/withspectrum/spectrum/blob/ba93c60928218dc1436a8c754324d012321a3a9f/mobile/components/InfiniteList/index.js#L51-L61

So if the `refetching` prop is passed in you shouldn't need all that dedup code

Comment (brianlovin) [reply mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: Same - I haven't duplicated any of the code, it's just my hunch at what's happening.

Comment (brianlovin) [reply mobile/views/DirectMessages/components/DirectMessageThreadsList.js]: Again I'm not sure what's going on. It looks like we *do* deduplicate dm threads in the web app as well, so maybe it is a server issue.

**Comment by brianlovin** [comment]
This took me a bit longer to figure out than I'd care to admit, but we're good now. No more instances of needed to dedupe children.

The underlying problem was that the `InfiniteList` component was avoiding refetching if the `refetching` prop was true. However, `refetch` and `fetchMore` are different network statuses in Apollo land. This means that when the list was paginated it would return `isRefetching: false, isFetchingMore: true` and `InfiniteList` wasn't listening for the `isFetchingMore` property :)

I've also gone ahead and cleaned up the `InfiniteList` api to use the `isFooing` prop naming scheme. E.g. `refetching => isRefetching` to be more clear :)

This is good to go.

**Review by mxstbr — APPROVED** [review]
Ahh awesome, great catch!! :100:
